[build]
  command = "pip install -r requirements.txt"
  publish = "templates"

[functions]
  # Tell Netlify where the code lives
  directory = "api" 
  included_files = ["templates/**"]

[[redirects]]
  from = "/api/*"
  # This points to the filename 'main' inside the 'api' folder
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200